os:
  - linux
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libyaml-dev
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install
script: coverage run -m test
after_success:
  - codecov
